<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="CommentList.aspx.cs" Inherits="WebApplication.CommentList" MasterPageFile="~/Site.Master" %>

<asp:Content runat="server" ContentPlaceHolderID="Main">
     <asp:GridView ID="GridView1" AutoGenerateColumns="false" runat="server" BackColor="White" 
            BorderColor="#DEDFDE" BorderStyle="None" 
            BorderWidth="1px" CellPadding="4" 
            ForeColor="Black" GridLines="Vertical" 
            AutoGenerateEditButton="false"   SelectMethod="GridView1_GetData"
            ItemType="WebApplication.Model.Comment" DataKeyNames="Id"
            AutoGenerateDeleteButton="True" DeleteMethod="Delete">
            <Columns>
                <asp:DynamicField DataField="Id"/>
                <asp:DynamicField DataField="Content" />
                <asp:DynamicField DataField="Date" />
            </Columns>
            <AlternatingRowStyle BackColor="White" />
            <FooterStyle BackColor="#CCCC99" />
            <HeaderStyle BackColor="#6B696B" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#F7F7DE" ForeColor="Black" HorizontalAlign="Right" />
            <RowStyle BackColor="#F7F7DE" />
            <SelectedRowStyle BackColor="#CE5D5A" Font-Bold="True" ForeColor="White" />
            <SortedAscendingCellStyle BackColor="#FBFBF2" />
            <SortedAscendingHeaderStyle BackColor="#848384" />
            <SortedDescendingCellStyle BackColor="#EAEAD3" />
            <SortedDescendingHeaderStyle BackColor="#575357" />
        </asp:GridView>
</asp:Content>
